server:
  port: 8040

gateway:
  host: localhost
  port: 18023

swagger:
  enable: true
  title: 百融接口文档
  description:
  serviceUrl: http://localhost:8080/
  version: 1.0.0
  controllers: com.sunyard.bairong.controller


spring:
  datasource:
    url: jdbc:oracle:thin:@//10.17.2.116:1521/ORCL
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: netloan
    password: nl123
    type: com.alibaba.druid.pool.DruidDataSource
  couchbase:
    bucket:
      name: jsh-netloan
      password: netloan123
    env:
      timeouts:
        connect: 100000ms
        key-value: 50000ms
        socket-connect: 30000ms
    bootstrap-hosts:
      - 10.17.2.112:8092
#      - 10.17.2.113:8092
      - 10.17.2.114:8092
#      - 10.17.2.115:8092

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    status-page-url: /actuator/info
    health-check-url: /actuator/health
    metadata-map:
      zone: dev
  client:
    fetch-registry: true
    register-with-eureka: true
    region: mingli
    availability-zones:
      mingli: dev
    service-url:
      dev: http://10.17.2.113:8761/eureka/,http://10.17.2.114:8761/eureka/,http://10.17.2.115:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:18022/uaa/oauth/user
      prefer-token-info: false

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  config:
    default:
      connectTimeout: 50000
      readTimeout: 30000
      loggerLevel: basic

bairong:
  apiCode: 3003724
#  apiName1: SandboxverApi
  apiName1: verificationApi
  apiName2: strategyApi
  bairongusername: jsyhStr
  bairongpassword: jsyhStr
  conf_id_package: DTV0000001
  strategy_id_package: STR0025269
#  strategy_id_page: STR0025709
  strategy_id_money: STR0025711

