spring:
  profiles:
    active: local
  #    active: local
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  application:
    name: netty-server
  jmx:
    enabled: false
# asdf
pagehelper:
  helperDialect: oracle
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

management:
  security:
    #关闭安全验证
    enabled: false