spring:
  profiles:
    active: local
  #    active: local
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  application:
    name: netty-server

  jmx:
    enabled: false
  messages:
    encoding: UTF-8
# asdf
pagehelper:
  helperDialect: oracle
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

management:
  security:
    #关闭安全验证
    enabled: false
banner:
  charset: UTF-8
server:
  tomcat:
  uri-encoding: UTF-8