server:
  port: 8021

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
  client:
    registerWithEureka: false
    fetchRegistry: false
    #注册中心之间互相注册
    serviceUrl:
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    #设为false，关闭自我保护
    enable-self-preservation: false
    #清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 3000
spring:
  cloud:
    inetutils:
      use-only-site-local-interfaces: true